---
title: "Bacterioplankton response to salinity (aka 2015 CSI Dispersal Experiment)"
author: "Alex Stucy, Jo Werba, Mike McCoy, Ariane Peralta"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
  fig_caption: true
---

```{r}
rm(list = ls())
setwd("~/GitHub/CSI_Dispersal/analyses") #set up by AP
```

```{r}
#Set Std Err and Conf Int
se <- function(x, ...) {
sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))
}
ci <- function(x, ...) {
1.96 * sd(x, na.rm = TRUE)
}
```

```{r}
#Set Source R Tools
source("../bin/DiversityFunctions.R")
source("../bin/MothurTools.R")
```

```{r}
#load required packages
require("vegan")
require("dplyr")
require("nlme")
require("reshape")
require("BiodiversityR")
require("ecodist")
require("ggplot2")
require("ade4")
require("png")
```

```{r}
#load design file - this is the real design file
design <- read.csv("../data/CSI_Design_ENV_NoSourceTanks.csv", row.names=1)
design

#set treatments (salinity levels)
treatments1 <- as.factor(design$Salinity)
levels(treatments1) <- c("0","5","9","13")
treatments2 <- as.factor(design$Dispersal)
levels(treatments2) <- c("2","3")
```

# Microbial Data - Need Mario's help to subset
```{r}
#load design file - this is the design file associated with microbes and need to get subset w/o mock
design_crobes <- read.csv("../data/design_CSI.csv", row.names=1)
design_crobes

# Import OTU data
# Import Raw Data
CSIdata.in <- read.otu("../data/CSI.shared")

# Remove Mock Community=CSI130
#CSIdata.in2 <- CSIdata.in[grepl("CSI[0-9][0-9]", rownames(CSIdata.in)), ] - not in data set

#design_crobes and CSIdata.in are not the same number of rows (?) - unsure where the mismatch is

#this is where we need to change to CSI data set and remove Number 1,2,3 from each row for microbes only in order to match design

# Identify source tanks where Number = 1, 2, 3
temp <- rownames(design_crobes[which(design_crobes$Number %in% c(1, 2, 3)), ])

# Remove sampeles from tank numbers 1, 2, 3
bac.design <- design_crobes[-(which(rownames(design_crobes) %in% temp)), ]
design <- droplevels(bac.design)

# Remove source tanks where Number = 1, 2, 3
CSIdata.in2 <- CSIdata.in2[-(which(rownames(CSIdata.in2) %in% temp)), ]
CSIdata.in2

# Remove OTUs with less than two occurences across all sites
CSIdata <- CSIdata.in2[, which(colSums(CSIdata.in2) >= 2)]

# Make Presence Absence Matrix
CSIdataPA <- (CSIdata > 0) * 1

# Make Relative Abundence Matrices
CSIdataREL <- CSIdata
for(i in 1:dim(CSIdata)[1]){
  CSIdataREL[i,] <- CSIdata[i,]/sum(CSIdata[i,])
}

# Log Transform Relative Abundances
CSIdataREL.log <- decostand(CSIdataREL, method="log")

# Import Taxonomy File
#CSI.tax <- read.tax(taxonomy = "../data/BD.0.03.cons.taxonomy")
```

```{r}
#import taxonomy file - simplified name
CSI.tax1 <- read.tax(taxonomy = "../data/CSI.0.03.cons.taxonomy")
#create tax table .csv and export
write.table(CSI.tax1, file = "tax.csv", sep = ",",
col.names = NA)
```

```{r}
#find minimum abundance to set rarefy
aa <- min(rowSums(CSI.datd))
aa
```

```{r}
#design3 <- read.csv("../data/design2_CSI.csv", row.names = 1)
#design3 <- read.csv("E:/Grad/Mothur/mothur/design_CSI.csv", row.names = 1)

newCSIdatd <- cbind(design3,CSIdataRELa)
row.names(CSIdataRELa) == row.names(design3) #matrices don't match dimensions
head(newCSIdatd)
row.names(newCSIdatd)

#remove unwanted rows!!!!
newCSIdata <- newCSIdatd[!rownames(newCSIdatd) %in% c("CSI044", "CSI051", "CSI071", "CSI123", "CSI128"), ]

salinity_adonis1 = adonis(newCSIdata[,-c(1:15)] ~ Salinity, method = "bray", data = newCSIdata, perm=1000)

dispersal_adonis1 = adonis(newCSIdata[,-c(1:15)] ~ Dispersal, method = "bray", data = newCSIdata, perm=1000)

disper_sal_adonis1 = adonis(newCSIdata[,-c(1:15)] ~ Dispersal*Salinity, method = "bray", data = newCSIdata, perm=1000)
dispersal_adonis1
salinity_adonis1
disper_sal_adonis1

capture.output(adonis(newCSIdata[,-c(1:15)] ~ Dispersal, method = "bray", data = newCSIdata, perm=1000), file="disp_permanova1.doc")
capture.output(adonis(newCSIdata[,-c(1:15)] ~ Salinity, method = "bray", data = newCSIdata, perm=1000), file="sal_permanova1.doc")
capture.output(adonis(newCSIdata[,-c(1:15)] ~ Dispersal*Salinity, method = "bray", data = newCSIdata, perm=1000), file="disper_sal_permanova1.doc")
```


```{r}
require("vegan")

CSIdatad <- CSI.datd[!rownames(CSI.datd) %in% c("CSI044", "CSI051", "CSI071", "CSI123", "CSI128"), ]
#min abundance is 20,726, we will sample to 20,000
CSIdatad.r1 <- rrarefy(CSIdatad, 20000)

# Fisher's Alpha
fisher1 <- fisher.alpha(CSIdatad.r1)
fisher1

# Species Richness
richness1 <- rowSums((CSIdatad.r1 >= 1))
richness1

# Shannon Diversity (my function gets the same answer)
shannon1 <- diversity(CSIdatad.r1, "shannon")

# Simpson's Evenness
simp.even1 <- diversity(CSIdatad.r1, "simpson")

# original simpsons code unsuccessful ("simp.even <- apply(CSIdata.r, 1, simp_even)") ... returned error "function: simp_even not found"

#Pielou's evenness
J1 <- shannon1/log(specnumber(CSIdatad.r1[,-c(1:1)]))

#combined richness, diversity, evenness
CSI.DIVaquamicrobes1 <- cbind(design2,richness1,shannon1,simp.even1,J1)
write.table(CSI.DIVaquamicrobes1, file="CSI.DIVaquamicrobes1.csv", sep=",", col.names=NA)
```

```{r}
# Hypothesis Testing
# First Check the order
length(design2$Salinity) == length(fisher1)
all.equal(gsub("-", "", rownames(design2)), names(fisher1))

fisher.lm1 <- lme(fisher1 ~ Salinity, random = ~1|Treatment, data = design2)
anova(fisher.lm1)
capture.output(anova(fisher.lm1), file="fisher.lm1.doc")

richness.lm1 <- lme(richness1 ~ Salinity, random = ~1|Treatment, data = design2)
anova(richness.lm1)
capture.output(anova(richness.lm1), file="richness.lm1.doc")

evenness.lm1 <- lme(simp.even1 ~ Salinity, random = ~1|Treatment, data = design2)
anova(evenness.lm1)
capture.output(anova(evenness.lm1), file="evenness.lm1.doc")

shannon.lm1 <- lme(shannon1 ~ Salinity, random = ~1|Treatment, data = design2)
anova(shannon.lm1)
capture.output(anova(shannon.lm1), file="shannon.lm1.doc")

library(agricolae)
summary(shannon.lm1)
shannon.lm1a <- lm(shannon1 ~ Salinity, data = CSI.DIVaquamicrobes1)
HSD1 <- HSD.test(shannon.lm1a,"Salinity", console=TRUE)

#salinity treatments not different in Shan Div (HSD test)
```

```{r}
p1 <- ggplot(CSI.DIVaquamicrobes1, aes(Salinity,shannon1))
boxplot1 <- p1 + geom_boxplot(aes(group=treatments1)) + theme_bw() + xlab("Salinity") + ylab("Shannon Diversity Index (H')")

ggsave("E:/Grad/Mothur/mothur/shannondiv1.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```


```{r}
CSIdataRELa1 <- CSIdataRELa[!rownames(CSIdataRELa) %in% c("CSI044", "CSI051", "CSI071", "CSI123", "CSI128"), ]

sampleREL.dist1 <- vegdist(CSIdataRELa1, method="bray")

# Principal Coordinates Analysis
CSI_pcoa1 <- cmdscale(sampleREL.dist1, k=3, eig=TRUE, add=FALSE)
  # Classical (Metric) Multidimensional Scaling; returns PCoA coordinates
  # eig=TRUE returns eigenvalues; k = # of dimensions to calculate

explainvar1a <- round(CSI_pcoa1$eig[1] / sum(CSI_pcoa1$eig), 3) * 100
explainvar2a <- round(CSI_pcoa1$eig[2] / sum(CSI_pcoa1$eig), 3) * 100
sum.eiga <- sum(explainvar1a, explainvar2a)

explainvar1a
explainvar2a
```

```{r}
#salinity
points1a <- cbind(as.data.frame(CSI_pcoa1$points), treatments1)
L.centroids1a <- melt(points1a, id="treatments1", measure.vars = c("V1", "V2"))
centroids1a <- cast(L.centroids1a, variable ~ treatments1, mean)
centroids.se1a <- cast(L.centroids1a, variable ~ treatments1, se)
centroids.sd1a <- cast(L.centroids1a, variable ~ treatments1, sd)

cent.dataframe1a <- t(data.frame(rbind(centroids1a[1,-1], centroids1a[2,-1],
                             centroids.sd1a[1,-1],centroids.sd1a[2,-1])))
colnames(cent.dataframe1a) <- c("V1", "V2", "V1e", "V2e")
cent.treats1a <- rownames(cent.dataframe1a)


##########################

#dispersal
points2 <- cbind(as.data.frame(CSI_pcoa1$points), treatments2)
L.centroids2 <- melt(points2, id="treatments2", measure.vars = c("V1", "V2"))
centroids2 <- cast(L.centroids2, variable ~ treatments2, mean)
centroids.se2 <- cast(L.centroids2, variable ~ treatments2, se)
centroids.sd2 <- cast(L.centroids2, variable ~ treatments2, sd)

cent.dataframe2 <- t(data.frame(rbind(centroids2[1,-1], centroids2[2,-1],
                             centroids.sd2[1,-1],centroids.sd2[2,-1])))
colnames(cent.dataframe2) <- c("V1", "V2", "V1e", "V2e")
cent.treats2 <- rownames(cent.dataframe2)
```

```{r}
#salinity
df1a <- as.data.frame(cent.dataframe1a)
plot1a <- ggplot(df1a, aes(x=V1, y=V2, colour=cent.treats1a)) + theme_bw() 
plot1a + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
theme(panel.background = element_blank()) + 
  geom_errorbarh(aes(xmax=V1+V1e, xmin=V1-V1e, height=0.01), colour="black") +    
  geom_errorbar(aes(ymax=V2+V2e, ymin=V2-V2e, width=0.01), colour="black") + 
  geom_point(size=5) +
  scale_colour_manual(labels = c("0","5","9","13"),   values = c("#FFFFCC", "#FFFF00", "#FF9933", "#66CC00")) +
  geom_point(shape=1, size = 5,colour = "black") +
theme(axis.title=element_text(size=18), axis.text=element_text(size=14), axis.text.x   = element_text(size=14), panel.border = element_rect(colour = "black",size=1.25)) + 
  theme(axis.ticks.length=unit(0.3,"cm")) + 
  xlab("PCoA 1 (21.7%)") + ylab("PCoA 2 (6.6%)") + 
  labs(color = "Salinity") +
  guides(colour = guide_legend(override.aes = list(pch=21, size = 4, colour="black",    
  fill=c("#FFFFCC", "#FFFF00", "#FF9933", "#66CC00")))) 

ggsave("E:/Grad/Mothur/mothur/16SrRNA_CSI_Rplot_Salinity.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)

####################################

df2 <- as.data.frame(cent.dataframe2)
plot2 <- ggplot(df2, aes(x=V1, y=V2, colour=cent.treats2)) + theme_bw() 
plot2 + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
theme(panel.background = element_blank()) + 
  geom_errorbarh(aes(xmax=V1+V1e, xmin=V1-V1e, height=0.01), colour="black") +    
  geom_errorbar(aes(ymax=V2+V2e, ymin=V2-V2e, width=0.01), colour="black") + 
  geom_point(size=5) +
  scale_colour_manual(labels = c("0","1","2","3"),   values = c("#FFFFCC", "#FFFF00", "#FF9933", "#66CC00")) +
  geom_point(shape=1, size = 5,colour = "black") +
theme(axis.title=element_text(size=18), axis.text=element_text(size=14), axis.text.x   = element_text(size=14), panel.border = element_rect(colour = "black",size=1.25)) + 
  theme(axis.ticks.length=unit(0.3,"cm")) + 
  xlab("PCoA 1 (21.7%)") + ylab("PCoA 2 (6.6%)") + 
  labs(color = "Dispersal Method") +
  guides(colour = guide_legend(override.aes = list(pch=21, size = 4, colour="black",    
  fill=c("#FFFFCC", "#FFFF00", "#FF9933", "#66CC00")))) 

ggsave("E:/Grad/Mothur/mothur/16SrRNA_CSI_Rplot_Dispersal.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```


